#!/bin/bash


#pushd ${OPENSHIFT_REPO_DIR}
hour=$(date '+%H')
if [ $hour -gt 3 ] && [ $hour -lt 11 ];then
      echo "  exit" 
else
	echo "bree"
	#exit
	#bundle exec rake import:hid RAILS_ENV="production" >> cron.log
fi

#popd 